spring:
  application:
    name: springboot-openfeign

server:
  port: 8086

# ======================== OpenFeign config ========================
feign:
  client:
    config:
      # default 对所有 @FeignClient 生效
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: FULL
      # 按 FeignClient name 单独配置
      user-service:
        connectTimeout: 3000
        readTimeout: 3000

# ======================== logging ========================
logging:
  level:
    com.quick.springbootopenfeign: debug
    com.quick.springbootopenfeign.client.UserFeignClient: DEBUG
