INSERT INTO t_user (name, email, age, status, role) VALUES
('张三',   'zhangsan@example.com',       25, 'active',   'admin'),
('张三丰', 'zhangsanfeng@example.com',   120,'active',   'viewer'),
('李四',   'lisi@example.com',           30, 'active',   'editor'),
('李四光', 'lisiguang@example.com',      80, 'inactive', 'viewer'),
('王五',   'wangwu@example.com',         22, 'active',   'viewer'),
('赵六',   'zhaoliu@example.com',        45, 'active',   'editor'),
('孙七',   'sunqi@example.com',          33, 'inactive', 'viewer'),
('周八',   'zhouba@example.com',         28, 'active',   'admin'),
('吴九',   'wujiu@example.com',          55, 'active',   'editor'),
('郑十',   'zhengshi@example.com',       40, 'inactive', 'viewer'),
('陈一',   'chenyi@example.com',         19, 'active',   'viewer'),
('刘二',   'liuer@example.com',          60, 'active',   'admin'),
('黄三',   'huangsan@example.com',       35, 'active',   'editor'),
('林四',   'linsi@example.com',          42, 'inactive', 'viewer'),
('何五',   'hewu@example.com',           27, 'active',   'viewer'),
('马六',   'maliu@example.com',          38, 'active',   'editor'),
('罗七',   'luoqi@example.com',          50, 'active',   'admin'),
('梁八',   'liangba@example.com',        31, 'inactive', 'viewer'),
('宋九',   'songjiu@example.com',        48, 'active',   'editor'),
('唐十',   'tangshi@example.com',        26, 'active',   'viewer');
